r"""Creates the alpha fixtures used by ``tests/readalpha.vpy``.

Run from the repository root with any Python 3:

    python tests/make-alpha-fixtures.py

Every file is three pixels wide and two pixels tall with hand-picked samples,
so the expected planes are easy to state in the validator. ``mono-alpha.png`` is
the exception: it is seven by five, because it is the source of the monochrome
heif and avif fixtures (``mono-alpha.heic`` and ``mono-alpha.avif``), which are
encoded from it with ``heif-enc`` and ``avifenc`` and cannot be written here.

Those container fixtures are generated by hand from the two png files this
script writes, because an encoder is the only way to produce them. Re-run these
commands from the repository root whenever a source png changes, with
``heif-enc``, ``avifenc`` and ``cjxl`` on ``PATH``, then re-run
``tests/readalpha.vpy``:

    heif-enc -q 100 -p x265:lossless=1 -o tests/fixtures/mono-alpha.heic tests/fixtures/mono-alpha.png
    avifenc --lossless --qalpha 100 -o tests/fixtures/mono-alpha.avif tests/fixtures/mono-alpha.png
    avifenc --lossless --qalpha 100 -d 10 -o tests/fixtures/mono-alpha-10.avif tests/fixtures/mono-alpha.png
    heif-enc -q 100 -p x265:lossless=1 -o tests/fixtures/alpha-rgba8.heic tests/fixtures/alpha-rgba8.png
    avifenc --lossless --qalpha 100 -o tests/fixtures/alpha-rgba8.avif tests/fixtures/alpha-rgba8.png
    cjxl -d 0 tests/fixtures/alpha-rgba8.png tests/fixtures/alpha-rgba8.jxl
    cjxl -d 0 tests/fixtures/jxl-gray10.pgm tests/fixtures/jxl-gray10.jxl
    cjxl -d 0 tests/fixtures/jxl-gray12.pgm tests/fixtures/jxl-gray12.jxl
    cjxl -d 0 tests/fixtures/jxl-rgba10.pam tests/fixtures/jxl-rgba10.jxl
    opj_compress -i tests/fixtures/alpha-l8.png -n 1 -o tests/fixtures/alpha-jp2-gray8.jp2
    opj_compress -i tests/fixtures/alpha-rgb8.png -mct 0 -n 1 -o tests/fixtures/alpha-jp2-rgb8.jp2
    opj_compress -i tests/fixtures/alpha-rgb8.png -mct 0 -n 1 -o tests/fixtures/alpha-j2k-rgb8.j2k
    opj_compress -i tests/fixtures/alpha-rgb8.png -mct 0 -I -q 35 -n 1 -o tests/fixtures/alpha-jp2-lossy.jp2
    magick tests/fixtures/alpha-rgba16.png -alpha off PNG48:target/j2k-rgb16.png
    opj_compress -i target/j2k-rgb16.png -mct 0 -n 1 -o tests/fixtures/alpha-jp2-rgb16.jp2

The yuv avif fixtures are the same kind of hand-made container: every one of
them states a matrix the frame properties can name, which is what moves a file
onto the plugin's own avif path. The three crops come from the
``sandbox/hitokage-sample`` files of the same layout, because those are the only
yuv avifs in the sandbox, and they are cut with ``magick`` through a png, so the
samples are the decoder's rgb of the crop re-encoded as yuv:

    magick "sandbox/hitokage-sample/avif-yuv420p.avif[64x48+0+0]" crop.png
    avifenc -q 100 --cicp 1/13/6 -r full --yuv 420 crop.png tests/fixtures/avif-yuv420p.avif
    magick "sandbox/hitokage-sample/avif-yuv422p.avif[64x48+0+0]" crop.png
    avifenc -q 100 --cicp 1/13/6 -r full --yuv 422 crop.png tests/fixtures/avif-yuv422p.avif
    magick "sandbox/hitokage-sample/avif-yuv444p10le.avif[32x24+0+0]" crop.png
    avifenc -q 100 -d 10 --cicp 1/13/6 -r full --yuv 444 crop.png tests/fixtures/avif-yuv444p10.avif

The alpha fixture is the four by four source below, encoded as the yuv page it
is the alpha of, so that the validator can state its planes: the samples are
neutral, which makes the two chroma planes 128 everywhere, and the alpha of the
four columns differs while the colour of the four rows differs:

    avifenc -q 100 --qalpha 100 --cicp 1/13/6 -r full --yuv 420 tests/fixtures/yuv-rgba8.png tests/fixtures/alpha-yuv420p.avif

``heif-enc`` is x265 through libheif and ``avifenc`` is aom through libavif; both
are asked for lossless output so the validator can state the exact samples, and
both keep the alpha plane at full quality. The heif encoder writes a monochrome
bitstream for a gray png and a 4:2:0 one for an rgb png, which is what makes
``mono-alpha.heic`` a monochrome-with-alpha fixture, and ``avifenc`` writes a
monochrome bitstream for the gray source, which is what makes
``mono-alpha.avif`` one. ``-d 10`` stores that one at ten bits per sample, which
is the ten bit avif: the encoder scales the eight bit source onto the ten bit
range, and the plugin hands the file out as ``Gray10`` holding exactly those
numbers, so the validator can state them instead of comparing against a
sixteen bit word the samples used to be left aligned in.

``alpha-rgba8.jxl`` is the jpeg xl copy of the same source, and it is the
fixture for the plugin's own jxl decode path, which is the only one that reads a
codestream's extra channels directly. ``jxl-gray10.jxl`` and ``jxl-gray12.jxl``
are the fixtures of a depth the ``image`` crate cannot name: both hold the
numbers one to twelve in a four by three picture and differ only in the depth
their ``MAXVAL`` states, one at ten bits per sample and one at twelve, which is
what tells a reader that moves the samples down out of the sixteen bit word by
the depth the file states rather than by a depth it was built with.
``jxl-rgba10.jxl`` is the same kind of source at ten bits with an alpha channel,
which is how the alpha plane of a deeper file gets a fixture of its own: it is
four interleaved planes of distinct numbers, so a plane that was shifted by the
wrong amount or filled with the wrong value shows up in the validator.
"""

from __future__ import annotations

import os
import struct
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")

WIDTH = 3
HEIGHT = 2

# Size of the source image the heif and avif fixtures are encoded from.
MONO_WIDTH = 7
MONO_HEIGHT = 5

# Size of the neutral source the yuv avif fixture with an alpha item is encoded
# from. Both sides are even, because a 4:2:0 encode needs a chroma plane of half
# the height and the width.
YUV_WIDTH = 4
YUV_HEIGHT = 4

# Size of the pgm sources of the two jpeg xl fixtures that state a depth between
# the eight bits and the sixteen a png can: four numbers wide and three tall, so
# the twelve samples one to twelve can be stated by position.
JXL_WIDTH = 4
JXL_HEIGHT = 3

# PNG color types.
GRAY = 0
RGB = 2
GRAY_ALPHA = 4
RGB_ALPHA = 6


def png(
    path: str,
    color_type: int,
    bit_depth: int,
    rows: list[list[int]],
    width: int = WIDTH,
    height: int = HEIGHT,
) -> None:
    """Writes an 8 or 16 bit PNG from the samples of every row."""
    if bit_depth == 8:
        packed = [bytes(row) for row in rows]
    else:
        packed = [b"".join(struct.pack(">H", sample) for sample in row) for row in rows]
    raw = b"".join(b"\x00" + row for row in packed)

    def chunk(kind: bytes, payload: bytes) -> bytes:
        crc = zlib.crc32(kind + payload) & 0xFFFFFFFF
        return struct.pack(">I", len(payload)) + kind + payload + struct.pack(">I", crc)

    header = struct.pack(">IIBBBBB", width, height, bit_depth, color_type, 0, 0, 0)
    document = (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )
    with open(path, "wb") as handle:
        handle.write(document)


def farbfeld(path: str, rows: list[list[tuple[int, int, int, int]]]) -> None:
    """Writes a farbfeld RGBA16 image."""
    height = len(rows)
    width = len(rows[0])
    payload = b"".join(
        struct.pack(">4H", *pixel)
        for row in rows
        for pixel in row
    )
    with open(path, "wb") as handle:
        handle.write(b"farbfeld" + struct.pack(">II", width, height) + payload)


def dds_dxt5(path: str) -> None:
    """Writes one 4x4 DXT5 block with an exact red/alpha checkerboard."""
    width = height = 4
    flags = 0x00081007  # caps, height, width, linear size and pixel format
    header = struct.pack(
        "<7I11I",
        124,
        flags,
        height,
        width,
        16,  # one DXT5 block
        0,
        0,
        *([0] * 11),
    )
    pixel_format = struct.pack(
        "<II4s5I",
        32,
        0x4,  # DDPF_FOURCC
        b"DXT5",
        0,
        0,
        0,
        0,
        0,
    )
    caps = struct.pack("<5I", 0x1000, 0, 0, 0, 0)  # DDSCAPS_TEXTURE

    alpha_indices = sum(
        (position % 2) << (position * 3) for position in range(width * height)
    )
    alpha_block = bytes((0, 255)) + alpha_indices.to_bytes(6, "little")
    color_block = struct.pack("<HHI", 0xF800, 0x0000, 0)
    with open(path, "wb") as handle:
        handle.write(b"DDS " + header + pixel_format + caps + alpha_block + color_block)


def netpbm(path: str, maximum: int, rows: list[list[int]], depth: int = 1) -> None:
    """Writes a binary grayscale PGM, or a four channel PAM when `depth` is four.

    A png can only state eight bits or sixteen, so a fixture whose nominal depth
    is between the two is a netpbm file: ``cjxl`` reads the ``MAXVAL`` of one as
    the depth of the codestream it writes, which is the only way to make a jpeg
    xl file that states ten or twelve bits per sample. The pgm form holds one
    channel and the pam form the four an alpha channel needs, both with the
    samples of a row interleaved and every sample as wide as the maximum needs.
    """
    if depth == 1:
        header = f"P5\n{len(rows[0])} {len(rows)}\n{maximum}\n"
    else:
        header = (
            f"P7\nWIDTH {len(rows[0]) // depth}\nHEIGHT {len(rows)}\n"
            f"DEPTH {depth}\nMAXVAL {maximum}\nTUPLTYPE RGB_ALPHA\nENDHDR\n"
        )
    if maximum < 256:
        payload = bytes(sample for row in rows for sample in row)
    else:
        payload = b"".join(struct.pack(">H", sample) for row in rows for sample in row)
    with open(path, "wb") as handle:
        handle.write(header.encode("ascii") + payload)


def tiff_rgba32f(path: str, pixels: list[list[float]]) -> None:
    """Writes an uncompressed 32 bit float RGBA TIFF."""
    payload = b"".join(struct.pack("<4f", *pixel) for pixel in pixels)

    ifd_offset = 8
    tags = [
        (256, 4, 1, WIDTH),  # ImageWidth
        (257, 4, 1, HEIGHT),  # ImageLength
        (258, 3, 4, None),  # BitsPerSample -> extra
        (259, 3, 1, 1),  # Compression: none
        (262, 3, 1, 2),  # PhotometricInterpretation: RGB
        (273, 4, 1, None),  # StripOffsets -> payload
        (277, 3, 1, 4),  # SamplesPerPixel
        (278, 4, 1, HEIGHT),  # RowsPerStrip
        (279, 4, 1, len(payload)),  # StripByteCounts
        (284, 3, 1, 1),  # PlanarConfiguration: chunky
        (339, 3, 4, None),  # SampleFormat -> extra
    ]
    ifd_size = 2 + len(tags) * 12 + 4
    bits_offset = ifd_offset + ifd_size
    formats_offset = bits_offset + 8
    data_offset = formats_offset + 8

    def entry(tag: int, kind: int, count: int, value: int) -> bytes:
        if kind == 3 and count == 1:
            return struct.pack("<HHIHH", tag, kind, count, value, 0)
        return struct.pack("<HHII", tag, kind, count, value)

    body = bytearray()
    for tag, kind, count, value in tags:
        if tag == 258:
            value = bits_offset
        elif tag == 273:
            value = data_offset
        elif tag == 339:
            value = formats_offset
        body += entry(tag, kind, count, value)

    document = bytearray(b"II\x2a\x00" + struct.pack("<I", ifd_offset))
    document += struct.pack("<H", len(tags)) + body + struct.pack("<I", 0)
    document += struct.pack("<4H", 32, 32, 32, 32)
    document += struct.pack("<4H", 3, 3, 3, 3)
    document += payload
    with open(path, "wb") as handle:
        handle.write(bytes(document))


def main() -> None:
    os.makedirs(FIXTURES, exist_ok=True)
    write = lambda name: os.path.join(FIXTURES, name)

    png(
        write("alpha-la8.png"),
        GRAY_ALPHA,
        8,
        [
            [10, 1, 20, 2, 30, 3],
            [40, 4, 50, 5, 60, 6],
        ],
    )
    png(
        write("alpha-la16.png"),
        GRAY_ALPHA,
        16,
        [
            [100, 65535, 200, 16384, 300, 32768],
            [400, 4096, 500, 2048, 600, 1],
        ],
    )
    png(
        write("alpha-rgba8.png"),
        RGB_ALPHA,
        8,
        [
            [1, 2, 3, 9, 4, 5, 6, 8, 7, 8, 9, 7],
            [10, 11, 12, 6, 13, 14, 15, 5, 16, 17, 18, 4],
        ],
    )
    png(
        write("alpha-rgba16.png"),
        RGB_ALPHA,
        16,
        [
            [
                1000, 2000, 3000, 100, 4000, 5000,
                6000, 200, 7000, 8000, 9000, 300,
            ],
            [
                10000, 11000, 12000, 400, 13000, 14000,
                15000, 500, 16000, 17000, 18000, 600,
            ],
        ],
    )
    farbfeld(
        write("alpha-rgba16.ff"),
        [
            [(1000, 2000, 3000, 100), (4000, 5000, 6000, 200)],
            [(7000, 8000, 9000, 300), (10000, 11000, 12000, 400)],
        ],
    )
    dds_dxt5(write("alpha-dds.dds"))
    png(
        write("alpha-rgb8.png"),
        RGB,
        8,
        [
            [1, 2, 3, 4, 5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14, 15, 16, 17, 18],
        ],
    )
    png(write("alpha-l8.png"), GRAY, 8, [[7, 8, 9], [10, 11, 12]])
    # The source of the monochrome-with-alpha heif and avif fixtures. seven wide
    # and five tall, with a different sample in almost every position, so a
    # plane that was shifted by a row, a column or one sample shows up in the
    # validator instead of cancelling out.
    png(
        write("mono-alpha.png"),
        GRAY_ALPHA,
        8,
        [
            [
                sample
                for x in range(MONO_WIDTH)
                for sample in (8 + 11 * x + 23 * y, 240 - 9 * x - 13 * y)
            ]
            for y in range(MONO_HEIGHT)
        ],
        width=MONO_WIDTH,
        height=MONO_HEIGHT,
    )
    # The source of the yuv avif fixture that holds an alpha item. Neutral
    # samples, so the chroma of the encode is 128 everywhere, with the colour of
    # the four rows and the alpha of the four columns differing.
    png(
        write("yuv-rgba8.png"),
        RGB_ALPHA,
        8,
        [
            [
                sample
                for x in range(YUV_WIDTH)
                for sample in (72 * y, 72 * y, 72 * y, 85 * x)
            ]
            for y in range(YUV_HEIGHT)
        ],
        width=YUV_WIDTH,
        height=YUV_HEIGHT,
    )
    tiff_rgba32f(
        write("alpha-rgba32f.tiff"),
        [
            [0.5, 0.25, 0.125, 0.25],
            [1.0, 2.0, 3.0, 0.75],
            [4.0, 5.0, 6.0, 0.0],
            [7.0, 8.0, 9.0, 1.0],
            [10.0, 11.0, 12.0, 0.5],
            [13.0, 14.0, 15.0, 0.125],
        ],
    )
    # The sources of the jpeg xl fixtures that state a depth between the eight
    # bits and the sixteen a png can. The two grayscale ones hold the numbers one
    # to twelve and differ only in the depth their header states, so a reader
    # that moved the samples down out of the sixteen bit word by a depth of its
    # own gives a different plane for one of them; the four channel one holds
    # four planes of distinct numbers at the same depth, so the alpha plane of a
    # deeper file is checked apart from the colour planes that share its word.
    samples = [
        [1 + x + JXL_WIDTH * y for x in range(JXL_WIDTH)] for y in range(JXL_HEIGHT)
    ]
    netpbm(write("jxl-gray10.pgm"), 1023, samples)
    netpbm(write("jxl-gray12.pgm"), 4095, samples)
    netpbm(
        write("jxl-rgba10.pam"),
        1023,
        [
            [
                sample
                for x in range(JXL_WIDTH)
                for sample in (
                    1 + x + JXL_WIDTH * y,
                    13 + x + JXL_WIDTH * y,
                    25 + x + JXL_WIDTH * y,
                    100 + x + JXL_WIDTH * y,
                )
            ]
            for y in range(JXL_HEIGHT)
        ],
        depth=4,
    )
    print(f"wrote the alpha fixtures to {FIXTURES}")


if __name__ == "__main__":
    main()
